# Destroys any cloud infrastructure that was deployed for the purpose of E2E testing.
name: aws-cloudfront-functions-cleanup

on:
  workflow_dispatch

jobs:
  aws-cloudfront-functions-cleanup:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn --immutable

      - name: Run Cloudfront Functions Cleanup
        run: node ./.github/workflows/cleanup/cleanupCloudfrontFunctions.js
