name: Delete All CloudFront Distributions

on:
  workflow_dispatch:

jobs:
  delete-cloudfront-distributions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install awscli jq -y

      - name: List, disable and delete all CloudFront distributions
        run: |
          # List all CloudFront distributions
          distributions=$(aws cloudfront list-distributions --query 'DistributionList.Items[*].Id' --output text)

          for distribution_id in $distributions; do
            echo "Disabling CloudFront distribution: $distribution_id"
            
            # Fetch the distribution config and ETag
            config=$(aws cloudfront get-distribution-config --id $distribution_id)
            etag=$(echo "$config" | jq -r '.ETag')
            config_json=$(echo "$config" | jq '.DistributionConfig')
            
            # Disable the distribution by setting Enabled to false
            updated_config=$(echo "$config_json" | jq '.Enabled = false')
            
            # Update the distribution to disable it
            aws cloudfront update-distribution \
              --id $distribution_id \
              --distribution-config "$updated_config" \
              --if-match "$etag"

            # Wait for the distribution to be fully disabled and deployed
            echo "Waiting for distribution to be disabled and deployed..."
            while true; do
              status=$(aws cloudfront get-distribution --id $distribution_id --query 'Distribution.Status' --output text)
              if [ "$status" == "Deployed" ]; then
                echo "Distribution $distribution_id is now deployed and disabled."
                break
              fi
              echo "Still waiting for deployment... checking again in 30 seconds."
              sleep 30
            done

            # Remove associated resources like aliases, behaviors, and origin groups
            echo "Removing associated resources from distribution: $distribution_id"
            # Fetch aliases, behaviors, etc., and remove them
            aliases=$(echo "$config_json" | jq '.Aliases.Items' | jq -r '.[]')
            if [ -n "$aliases" ]; then
              echo "Removing aliases..."
              updated_config=$(echo "$updated_config" | jq '.Aliases.Quantity = 0 | .Aliases.Items = []')
            fi

            # Check if distribution is fully disabled with no ongoing invalidations
            invalidations=$(aws cloudfront list-invalidations --distribution-id $distribution_id --query 'InvalidationList.Items')
            if [ -n "$invalidations" ]; then
              echo "Waiting for active invalidations to complete..."
              sleep 30  # Add a waiting time before deletion if invalidations are present
            fi

            # Fetch a new ETag before deletion after config changes
            new_etag=$(aws cloudfront get-distribution-config --id $distribution_id --query 'ETag' --output text)

            # Now attempt to delete the distribution
            echo "Deleting CloudFront distribution: $distribution_id"
            aws cloudfront delete-distribution --id $distribution_id --if-match "$new_etag"
          done
